name: Tests
on:
  - pull_request
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: npm t
